sudo: required
language: python
jdk: openjdk8
services: docker
python: '3.6'
matrix:
  fast_finish: true
install:
- mkdir /tmp/nextflow
- cd /tmp/nextflow
- wget -qO- get.nextflow.io | bash
- sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
- pip install --upgrade pip
- pip install nf-core
- mkdir ${TRAVIS_BUILD_DIR}/tests && cd ${TRAVIS_BUILD_DIR}/tests
- sudo apt-get install npm && npm install -g markdownlint-cli
- sudo apt-get install libarchive-dev
- mkdir /tmp/singularity
- cd /tmp/singularity
- wget https://github.com/singularityware/singularity/releases/download/2.5.2/singularity-2.5.2.tar.gz
- tar xvf singularity-2.5.2.tar.gz
- cd singularity-2.5.2
- "./configure --prefix=/usr/local"
- make
- sudo make install
env:
  matrix:
  - NXF_VER=19.04.1
  global:
    secure: eJq3JN+G/ikeMUsdHtGAdjRw1MEErEONI+kgSI8w8dErNDLO8ce49KLuY9JA1rc/+4PC9Fy6TAo/p0SD9iKHzJqZm10G+NLxzthX3oRgH1GmHVER8hoFqByg7B//NUfQtqFjKxG2LnYo5TJtZPq1UzTBYj+W/qBAyWSvL5retdaAx5D8omAncGD1IrxmxVrC/3Kp9T/qUZ42zzM1zaLb13ZRpVB2kjWsx4R24fEhWCkcNpwwHBfiHwg5CragiYu+c+XS1HDZNBjhkO09Q0A+k7qmj72lq9yPIEeoOsiPaWp6FqUVuezTk+bp51SlrXxhvP/1cQsjrTma4HLoGJhrfZtVOYRv1svTzstWIr2BXvKlr9Ek6i8L4KoAZqEWTcrSZl1TbxfXH4N6E0dsQkwlrMyISQh64OaZ2+Z1L+sfeDavIySJShw/5qjK9qbeExwmgO99M1mmQp/GgjqS7vmhUKNZlY+CHL5NMQUbc20D72ebHatY7EWYCVpdq5wogGy0GvNr/U/FN7GInkOxplDpG1aj940i+Rkf+1MU3yIYQymsfogUk1Q/0Iu0p3k7us5cZQXQmPH8kxYaxx2IUjubOb3gKzSsfVHMCDLy0eiA1On+tSariEtb50aFJ8C6qk9NXlDlG65TFbpBgP8sWBp/8eKO8+EzurljQP/AnAm9MBU=
script:
- nextflow run mturkson23/chipimputation -r master -profile test,singularity
